### ISSUE TITLE
linux segmentation fault

### ISSUE THREAD

**Issue by arblake** [phreda4/r3#1]
Hi. 

"
r3vm - PHREDA
compile:main.r3... ok.
inc:8 - words:408 - code:14Kb - data:34Kb - free:989Kb

Segmentation fault (core dumped)
"
Ubuntu latest. Doing strace has no clues.

**Comment by phreda4** [comment]
This version is not ready for linux now, try https://github.com/phreda4/r3d4 or if you are advance programer, you can try to  convert posix library (for system calls), I think the VM is almost work, the VM is https://github.com/phreda4/r3evm
